services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: beetie
      POSTGRES_PASSWORD: TheSecretKingdom3319
      POSTGRES_DB: db1

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 32773:80
    environment:
      PGADMIN_DEFAULT_EMAIL: beetie@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: TheSecretKingdom3319
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'